# Generated by Django 4.0.1 on 2022-02-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='update_date',
            field=models.DateTimeField(default='2022-02-10T15:58:44.767594-06:00', verbose_name='Last Updated'),
        ),
    ]
