# Generated by Django 4.0.1 on 2022-02-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topic_id_alter_topic_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='image_url',
        ),
    ]
