# Generated by Django 4.0.1 on 2022-02-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_remove_topic_image_remove_topic_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='lower_content',
        ),
    ]
