# Generated by Django 4.0.1 on 2022-02-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_remove_topic_lower_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
