# Generated by Django 4.0.1 on 2022-02-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_alter_subject_id_alter_subtopic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='old_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='old_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='old_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
