# Generated by Django 4.0.1 on 2022-02-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_alter_subject_old_url_alter_subtopic_old_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='new_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
