# Generated by Django 4.0.1 on 2022-02-13 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_topic_new_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 13, 0, 29, 825872), verbose_name='Last Updated'),
        ),
    ]
