# Generated by Django 4.0.1 on 2022-03-03 23:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_alter_topic_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 18, 13, 15, 760330), verbose_name='Last Updated'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='topics.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
