# Generated by Django 4.0.1 on 2022-01-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papermasters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
