# Generated by Django 4.0.1 on 2022-01-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papermasters', '0002_topic_meta_title_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='old_url',
            field=models.URLField(blank=True),
        ),
    ]
