# Generated by Django 4.0.1 on 2022-01-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papermasters', '0003_topic_old_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
