# Generated by Django 4.0.1 on 2022-02-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papermasters', '0004_alter_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='update_date',
            field=models.DateTimeField(default='2022-01-31T15:58:44.767594-06:00', verbose_name='Last Updated'),
        ),
    ]
