# Generated by Django 4.0.1 on 2022-02-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papermasters', '0006_subject_content_subject_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
