# Generated by Django 4.0.1 on 2022-02-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papermasters', '0007_alter_subject_description_alter_subtopic_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
