# Generated by Django 4.0.1 on 2022-01-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toplevel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
