# Generated by Django 4.0.1 on 2022-02-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toplevel', '0002_alter_resource_slug_alter_service_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
